### PR TITLE
Add warning formspec, misc changes

### PR DESCRIPTION
**Pull request by rubenwardy**
**Don't squash and merge!** - It's best to keep the commits separate as they do different things. Some commits may be squashed if you think they're too similar however.

Sorry for not making these separate PRs, I'm developing to place directly on my server

* Add mute function which will be used in future for variable length mutes.
* Add warning formspec on first violation.
* Add callback support for custom violation handlers.
* See commits

### CODE REVIEW

**Comment by rubenwardy** [comment]
This is now done, just needs testing on my server

**Comment by rubenwardy** [comment]
```
$ luacheck .
Checking init.lua                                 OK

Total: 0 warnings / 0 errors in 1 file
```

**Comment by sofar** [comment]
I'd like to rewrite the formspec stuff to use `fsc` if you don't mind, at some point.

**Comment by rubenwardy** [comment]
That doesn't make sense as no data is submitted and it just adds unneeded code

**Pull request merged**
